name: tty-os
description: A fully TTY-based OS with TUI apps for everything.
base-image: ghcr.io/ublue-os/base-main  # base-main = no desktop, just the atomic base
image-version: 42

modules:
  - from-file: packages.yml
  - from-file: greetd.yml
  - from-file: system-config.yml
  - type: signing
