name: Build ISO

on:
  workflow_dispatch: # manual trigger
  release:
    types: [created]

jobs:
  build-iso:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Build ISO
        uses: jasonn3/build-container-installer@v1.4.0
        id: build
        with:
          image_repo: ghcr.io/uubroot
          image_name: tty-os
          image_tag: latest
          version: 42
          iso_name: tty-os.iso

      - name: Upload ISO to release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          files: |
            tty-os.iso
            tty-os.iso-CHECKSUM
      - name: Upload as artifact (for manual runs)
        if: github.event_name == 'workflow_dispatch'
        uses: actions/upload-artifact@v4
        with:
          name: tty-os.iso
          path: ${{ steps.build.outputs.iso_path }}
